name: Build RecoToSSD Images
on:
  schedule:
    - cron: 0 */12 * * * # Once every 3 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  fetch_build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Packages and install cgpt
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade \
            -o Dpkg::Options::=--force-confold \
            -o Dpkg::Options::=--force-confdef \
            -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
          sudo apt-get install cgpt \
            -o Dpkg::Options::=--force-confold \
            -o Dpkg::Options::=--force-confdef \
            -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
      - name: Build RecoToSSD and Upload to GitHub Releases
        run: PUSH_TO_GITHUB=1 THREADS=5 ./fetch_iter.sh
        env:
          GH_TOKEN: ${{ github.token }}
