name: Build RecoToSSD Images
on:
  schedule:
    - cron: 0 */6 * * * # Once every 6 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  fetch_build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Clean old packages
        run: |
          sudo rm -rf /usr/local/lib/android \
            /usr/share/dotnet \
            /opt/ghc \
            /usr/local/.ghcup \
            /opt/hostedtoolcache \
           /usr/local/graalvm \
           /usr/local/share/powershell \
           /usr/local/share/chromium \
           /usr/local/lib/node_modules \
           "$AGENT_TOOLSDIRECTORY"
          # Docker
          sudo docker image prune --all --force
          # Big useless bs
          sudo apt-get purge -y '^aspnetcore-.*'
          sudo apt-get purge -y '^dotnet-.*' --fix-missing
          sudo apt-get purge -y '^llvm-.*' --fix-missing
          sudo apt-get purge -y 'php.*' --fix-missing
          sudo apt-get purge -y '^mongodb-.*' --fix-missing
          sudo apt-get purge -y '^mysql-.*' --fix-missing
          sudo apt-get purge -y azure-cli \
            google-chrome-stable \
            firefox powershell \
            mono-devel \
            snapd \
            libgl1-mesa-dri \
            google-cloud-sdk \
            google-cloud-cli \
            microsoft-edge-stable \--fix-missing
          sudo apt-get autoremove --purge -y
          sudo apt-get clean
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: docker build -t arch-image .
      - name: Run the command
        run: docker run arch-image ./fetch_iter.sh --privileged -v /dev:/dev -v /mnt:/mnt
