name: Build RecoToSSD Images
on:
  schedule:
    - cron: 0 0 */100 * * # Once every 3 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  fetch_build_and_upload:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
        # Setup arch
      - name: Update packages and install some necessities
        run: pacman -Syu --needed --noconfirm git jq github-cli unzip
      - name: Create a new user
        run: useradd --create-home runner && (printf "runner ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/runner)
      - name: Install yay
        run: sudo -urunner bash -c "cd && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -sri --needed --noconfirm && rm -rf ~/.cache ~/yay"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CGPT (via vboot-utils)
        run: sudo -urunner yay -S --noconfirm vboot-utils
      - name: Fix Dubious Ownership
        run: git config --global --add safe.directory '*' && sudo -urunner git config --global --add safe.directory '*'
      - name: Build RecoToSSD and Upload to GitHub Releases
        run: sudo -E -urunner PUSH_TO_GITHUB=1 THREADS=5 ./fetch_iter.sh
        env:
          GH_TOKEN: ${{ github.token }}
